export interface TemplateData {
  //   navbarColor: string;
  //   buttonColor: string;
  //   fontFamily: string;
  //   logoName: string;
  //   logoColor: string;
  //   navigationLinks: Array<{ name: string; link: string }>;
  //   navigationLinksColor: string;
  //   headerTitle: string;
  //   headerDescription: string;
  //   headerImage: string;
  //   headerTextColor: string;
  //   descriptionTextColor: string;
  //   aboutTitle: string;
  //   aboutDoctorName: string;
  //   aboutDescription: string;
  //   aboutExtraText: string;
  //   aboutImage: string;
  //   aboutButtonColor: string;
  //   blogTitle: string;
  //   blogContent: string;
  //   blogImages: string[];
  //   blogButtonColor: string;
  //   contactBookingText: string;
  //   contactInstagramName: string;
  //   contactInstagramLink: string;
  //   contactFacebookName: string;
  //   contactFacebookLink: string;
  //   contactPhone: string;
  //   contactEmail: string;
  //   contactLocation: string;
  //   services: Array<{ title: string; description: string; icon: string }>;
  //   portfolioSlides: Array<{
  //     id: number;
  //     title: string;
  //     description: string;
  //     image: string;
  //   }>;
  //   portfolioTestimonials: Array<{
  //     id: number;
  //     name: string;
  //     quote: string;
  //     image: string;
  //   }>;
  //   portfolioButtonColor: string;
  //   footerLinks: Array<{ name: string; link: string }>;
  backgroundColor?: string;
  navbarColor?: string;
  logoName?: string;
  logoColor?: string;
  logoIcon?: string;
  buttonColor?: string;
  fontFamily?: string;
  fontFamilyClass?: string;
  headerTitle?: string;
  headerSubtitle?: string;
  headerDescription?: string;
  headerImage?: string;
  titleTextColor?: string;
  subtitleTextColor?: string;
  descriptionTextColor?: string;
  aboutTitle?: string;
  aboutDoctorName?: string;
  aboutDescription?: string;
  aboutExtraText?: string;
  aboutImage?: string;
  aboutButtonColor?: string;
  blogTitle?: string;
  blogContent?: string;
  blogImages?: string[];
  blogButtonColor?: string;
  contactBookingText?: string;
  contactInstagramName?: string;
  contactInstagramLink?: string;
  contactFacebookName?: string;
  contactFacebookLink?: string;
  contactPhone?: string;
  contactEmail?: string;
  contactLocation?: string;
  services?: Array<{ title: string; description: string; icon: string }>;
  portfolioSlides?: Array<{
    title: string;
    description: string;
    image: string;
  }>;
  portfolioTestimonials?: Array<{ name: string; quote: string; image: string }>;
  portfolioButtonColor?: string;
  footerLinks?: Array<{ name: string; link: string }>;
  navigationLinks?: Array<{ name: string; link: string }>;
  navigationLinksColor?: string; // إضافة navLinksTextColor
}
