"use client";
import { usePathname } from "next/navigation";
// import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isTemplatePage = pathname.startsWith("/templates/");

  return (
    <html lang="en">
      <body>
        {!isTemplatePage && <Navbar />}
        {/* ✅ إخفاء النافبار إذا كان المستخدم في templates */}
        <main>{children}</main>
        {!isTemplatePage && <Footer />}
        {/* ✅ إخفاء الفوتر إذا كان المستخدم في templates */}
      </body>
    </html>
  );
}
